let g:plugged_dir_path = expand('$HOME/.vim/plugged')
let g:autoload_plug_path = expand('$HOME/.vim/autoload/plug.vim')

" load plugins
if empty(glob(g:autoload_plug_path))
  silent exec "!curl -fLo ".g:autoload_plug_path." --create-dirs "
    \ ."https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
endif

" check for plugged dir
if empty(glob(g:plugged_dir_path))
  silent exec "!mkdir ".g:plugged_dir_path
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif


call plug#begin(g:plugged_dir_path)
  Plug 'christoomey/vim-tmux-navigator'
  Plug 'junegunn/fzf', {'do': {-> fzf#install()}}
  Plug 'junegunn/fzf.vim'
  Plug 'tpope/vim-fugitive'
  Plug 'tpope/vim-surround'
  Plug 'tpope/vim-commentary'
  Plug 'tpope/vim-dadbod'
  Plug 'kristijanhusak/vim-dadbod-ui', {'do': 'git am ../../jump-to-fk-fix.patch'}
  Plug 'diepm/vim-rest-console'
  Plug 'tsandall/vim-rego'
  Plug 'pgr0ss/vim-github-url'
  Plug 'joshdick/onedark.vim'
  Plug 'vim-test/vim-test'
  Plug 'preservim/vimux'

  if has('python3')
    Plug 'petobens/poet-v'
  endif
  
  if has('nvim')
    Plug 'nvim-lua/plenary.nvim'
    Plug 'neovim/nvim-lspconfig'
    Plug 'hrsh7th/nvim-cmp' 
    Plug 'hrsh7th/cmp-nvim-lsp'
    Plug 'jose-elias-alvarez/null-ls.nvim'
    Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
    Plug 'mfussenegger/nvim-dap'
  endif

call plug#end()


" vim configs
runtime! rcfiles/*.vim
" plugin configs
runtime! rcplugins/*.vim

if has('nvim')
  runtime! rcplugins/*.lua
endif
