"Basic/core settings for Vim itself
runtime! config/plug-list.vim "Adding plugins via junegunnvim-plug
runtime! config/core.vim

"Settings
runtime! config/functions.vim
runtime! config/colorscheme.vim
runtime! config/plug-conf/*.vim "plugin settings - .vim files
runtime! config/plug-conf/*.lua "plugin settings - .lua files

"Mappings
runtime! config/mappings.vim

