let g:plugged_dir_path = '~/.vim/plugged'
let g:autoload_plug_path = '~/.vim/autoload/plug.vim'

" load plugins
if empty(glob(g:autoload_plug_path))
  silent exec "!curl -fLo ".g:autoload_plug_path." --create-dirs "
    \ ."httpg://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
endif

" check for plugged dir
if empty(glob(g:plugged_dir_path))
  silent exec "!mkdir ".g:plugged_dir_path
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

"Plugins
runtime! plug-list.vim

"Settings
runtime! settings/*

"Plug-configs
runtime! plug-configs/*.vim

if has('nvim')
  runtime! plug-configs/*.lua
endif
